name: Unit Tests

on: 
  pull_request:
    types: [opened]
  push:
    branches: 
    - main
    - develop
    - 'feature-**'
    

jobs:
  tests: 
    runs-on: [ubuntu-latest, windows-latest]

    strategy:
      matrix: 
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: tests
      run: npm test
